"""Dynamic MkDocs hook for generating virtual documentation pages from Python docstrings."""

import os
import shutil
from mkdocs.structure.files import File


def on_files(files, config):
    """Dynamically generate virtual markdown documentation pages for all Python modules in src/."""
    if not hasattr(config.plugins, "_current_plugin"):
        config.plugins._current_plugin = None

    docs_dir = config["docs_dir"]
    repo_root = os.path.abspath(os.path.join(docs_dir, ".."))
    src_dir = os.path.join(repo_root, "src")

    # Generate virtual index.md overview from README.md if no index.md on disk
    if not files.get_file_from_path("index.md"):
        readme_path = os.path.join(repo_root, "README.md")
        overview_content = ""
        if os.path.isfile(readme_path):
            with open(readme_path, "r", encoding="utf-8") as rf:
                overview_content = rf.read()
        else:
            overview_content = "# ChessWithQuests\n\nAutogenerated API Documentation.\n"

        overview_content += "\n\n---\n\n## Reference Architecture Diagram\n- [Architecture Diagram](https://app.diagrams.net/#G19OY7iySOQWRAZDFKy1r-7tJKG_L-_Qn8#%7B%22pageId%22%3A%22C5RBs43oDa-KdzZeNtuy%22%7D)\n"
        index_file = File.generated(
            config,
            "index.md",
            content=overview_content,
        )
        files.append(index_file)

    for root, _, filenames in os.walk(src_dir):
        for f in sorted(filenames):
            if not f.endswith(".py"):
                continue

            full_path = os.path.join(root, f)
            rel_path = os.path.relpath(full_path, src_dir)
            parts = rel_path.split(os.sep)
            parts[-1] = os.path.splitext(parts[-1])[0]

            if parts[-1] == "__init__":
                if len(parts) == 1:
                    # Root package overview is covered by docs/index.md
                    continue
                dotted_path = ".".join(parts[:-1])
                doc_uri = "/".join(parts[:-1]) + "/index.md"
                title = f"{parts[-2].capitalize()} Package (`{dotted_path}`)"
            else:
                dotted_path = ".".join(parts)
                doc_uri = "/".join(parts) + ".md"
                title = f"{parts[-1].capitalize()} (`{dotted_path}`)"

            # Avoid collisions with static docs if already present
            if files.get_file_from_path(doc_uri):
                continue

            content = f"# {title}\n\n::: {dotted_path}\n"
            gen_file = File.generated(
                config,
                doc_uri,
                content=content,
            )
            files.append(gen_file)

    return files


def on_post_build(config):
    """Ensure site/index.html is available."""
    site_dir = config["site_dir"]
    index_html = os.path.join(site_dir, "index.html")
    if not os.path.exists(index_html):
        for candidate in ["index.html", "__init__/index.html", "src/index.html"]:
            src = os.path.join(site_dir, candidate)
            if os.path.exists(src):
                shutil.copyfile(src, index_html)
                print(f"Generated site/index.html from {candidate}")
                break
