import os
import pytest


def test_docs_index_references_all_documentation():
    """Verify that docs/index.md is the central overview and static DOCS.md is removed."""
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    index_md = os.path.join(repo_root, "docs", "index.md")
    docs_md = os.path.join(repo_root, "DOCS.md")

    assert os.path.isfile(index_md), "docs/index.md must exist as central overview"
    assert not os.path.exists(docs_md), "DOCS.md should not exist (superseded by dynamic docs)"

    with open(index_md, encoding="utf-8") as f:
        content = f.read()

    assert "ChessWithQuests" in content
    assert "Overview" in content
    assert "Architecture & Modules" in content


def test_agents_rule_requires_index_update():
    """Verify AGENTS.md mandates autogenerated documentation via MkDocs."""
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    agents_file = os.path.join(repo_root, "AGENTS.md")

    with open(agents_file, encoding="utf-8") as f:
        content = f.read()

    assert "mkdocs" in content.lower()
    assert "autogenerated" in content.lower()
