import ast
import os
import subprocess
import pytest


def test_all_source_modules_have_google_docstrings():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src_dir = os.path.join(repo_root, "src")
    missing = []

    for root, _, files in os.walk(src_dir):
        for file in sorted(files):
            if file.endswith(".py"):
                path = os.path.join(root, file)
                with open(path, "r", encoding="utf-8") as f:
                    tree = ast.parse(f.read(), filename=path)

                mod_doc = ast.get_docstring(tree)
                if not mod_doc:
                    missing.append(f"{path}: missing module docstring")

                for node in tree.body:
                    if isinstance(node, ast.ClassDef):
                        class_doc = ast.get_docstring(node)
                        if not class_doc:
                            missing.append(f"{path} Class {node.name}: missing class docstring")
                        for sub in node.body:
                            if isinstance(sub, ast.FunctionDef):
                                if not sub.name.startswith("_") or sub.name == "__init__":
                                    func_doc = ast.get_docstring(sub)
                                    if not func_doc:
                                        missing.append(
                                            f"{path} Class {node.name}.{sub.name}: missing docstring"
                                        )
                    elif isinstance(node, ast.FunctionDef):
                        if not node.name.startswith("_"):
                            func_doc = ast.get_docstring(node)
                            if not func_doc:
                                missing.append(f"{path} Function {node.name}: missing docstring")

    assert not missing, f"Missing docstrings found:\n" + "\n".join(missing)


def test_all_docs_use_mkdocstrings_directives():
    """Verify that dynamic docs hook generates mkdocstrings ':::' directives for source modules."""
    import mkdocs.config
    from mkdocs.structure.files import get_files
    import sys

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    scripts_dir = os.path.join(repo_root, ".github", "scripts")
    if scripts_dir in sys.path:
        sys.path.remove(scripts_dir)
    sys.path.insert(0, scripts_dir)
    sys.modules.pop("mkdocs_hooks", None)

    import mkdocs_hooks

    cfg = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
    cfg = mkdocs_hooks.on_config(cfg)
    files = get_files(cfg)
    files = mkdocs_hooks.on_files(files, cfg)

    generated_files = [f for f in files if getattr(f, "_content", None)]
    assert (
        len(generated_files) >= 25
    ), f"Expected dynamic files generated, found {len(generated_files)}"
    for f in generated_files:
        if f.src_uri != "index.md" and not f.src_uri.startswith("notes/"):
            assert ":::" in f._content, f"Generated file {f.src_uri} missing ':::' directive"


def test_dynamic_notes_incorporation():
    """Verify that notes are dynamically discovered, incorporated into navigation and generated."""
    import mkdocs.config
    from mkdocs.structure.files import get_files
    import sys

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    scripts_dir = os.path.join(repo_root, ".github", "scripts")
    if scripts_dir in sys.path:
        sys.path.remove(scripts_dir)
    sys.path.insert(0, scripts_dir)
    sys.modules.pop("mkdocs_hooks", None)

    import mkdocs_hooks

    cfg = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
    cfg = mkdocs_hooks.on_config(cfg)
    files = get_files(cfg)
    files = mkdocs_hooks.on_files(files, cfg)

    # 1. Verify virtual files generated for all notes
    expected_notes = [
        "notes/chess_rules.md",
        "notes/object_model.md",
        "notes/reference_diagram.md",
        "notes/upstream_base.md",
        "notes/index.md",
    ]
    file_map = {f.src_uri: f for f in files}
    for note_uri in expected_notes:
        assert note_uri in file_map, f"Expected {note_uri} to be generated by hook"

    # 2. Verify all generated note files retain their source content
    for note_name in [
        "chess_rules.md",
        "object_model.md",
        "reference_diagram.md",
        "upstream_base.md",
    ]:
        note_path = os.path.join(repo_root, "notes", note_name)
        with open(note_path, "r", encoding="utf-8") as f:
            expected_content = f.read()
        gen = file_map[f"notes/{note_name}"]
        assert getattr(gen, "_content", "") == expected_content, f"Content mismatch for {note_name}"

    # 3. Verify notes/index.md contains links to each note
    notes_index_file = file_map["notes/index.md"]
    notes_index_content = getattr(notes_index_file, "_content", "")
    assert "# Architecture & Design Notes" in notes_index_content
    for note_name in [
        "chess_rules.md",
        "object_model.md",
        "reference_diagram.md",
        "upstream_base.md",
    ]:
        assert note_name in notes_index_content, f"notes/index.md missing link to {note_name}"

    # 4. Verify on_config successfully populates Notes in config["nav"]
    test_cfg = {"nav": [{"Overview": "index.md"}], "docs_dir": os.path.join(repo_root, "src")}
    updated_cfg = mkdocs_hooks.on_config(test_cfg)
    notes_entry = next(
        (item for item in updated_cfg["nav"] if isinstance(item, dict) and "Notes" in item), None
    )
    assert notes_entry is not None, "Notes section missing in nav"
    assert "notes/index.md" in notes_entry["Notes"]
    for note_name in [
        "chess_rules.md",
        "object_model.md",
        "reference_diagram.md",
        "upstream_base.md",
    ]:
        assert f"notes/{note_name}" in notes_entry["Notes"], f"notes/{note_name} missing from nav"

    # 5. Verify dynamic discovery works when a temporary note file is placed in notes/
    temp_note_path = os.path.join(repo_root, "notes", "temp_test_note.md")
    try:
        with open(temp_note_path, "w", encoding="utf-8") as f:
            f.write("# Temp Test Note\nTemporary note content for testing dynamic discovery.")

        # Test on_config with temp note
        cfg_dyn = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
        cfg_dyn = mkdocs_hooks.on_config(cfg_dyn)
        dyn_notes_entry = next(
            (item for item in cfg_dyn["nav"] if isinstance(item, dict) and "Notes" in item), None
        )
        assert dyn_notes_entry is not None
        assert "notes/temp_test_note.md" in dyn_notes_entry["Notes"]

        # Test on_files with temp note
        files_dyn = get_files(cfg_dyn)
        files_dyn = mkdocs_hooks.on_files(files_dyn, cfg_dyn)
        dyn_map = {f.src_uri: f for f in files_dyn}
        assert "notes/temp_test_note.md" in dyn_map
        assert getattr(dyn_map["notes/temp_test_note.md"], "_content", "") == (
            "# Temp Test Note\nTemporary note content for testing dynamic discovery."
        )
        assert "temp_test_note.md" in getattr(dyn_map["notes/index.md"], "_content", "")
    finally:
        if os.path.exists(temp_note_path):
            os.remove(temp_note_path)


def test_dynamic_notes_nav_variants():
    """Verify on_config followed by on_files works when nav has no Notes, empty Notes, or None Notes."""
    import mkdocs.config
    from mkdocs.structure.files import Files
    import sys

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    scripts_dir = os.path.join(repo_root, ".github", "scripts")
    if scripts_dir in sys.path:
        sys.path.remove(scripts_dir)
    sys.path.insert(0, scripts_dir)
    sys.modules.pop("mkdocs_hooks", None)

    import mkdocs_hooks

    # Variant A: No Notes section in nav
    cfg_none = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
    cfg_none["nav"] = [{"Overview": "index.md"}]
    cfg_none = mkdocs_hooks.on_config(cfg_none)
    notes_entries = [item for item in cfg_none["nav"] if isinstance(item, dict) and "Notes" in item]
    assert len(notes_entries) == 1, "Expected exactly one Notes entry in nav"
    assert "notes/index.md" in notes_entries[0]["Notes"]
    assert "notes/chess_rules.md" in notes_entries[0]["Notes"]

    # Variant B: nav has - Notes: [] (empty list)
    cfg_empty = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
    cfg_empty["nav"] = [{"Overview": "index.md"}, {"Notes": []}]
    cfg_empty = mkdocs_hooks.on_config(cfg_empty)
    notes_entries = [
        item for item in cfg_empty["nav"] if isinstance(item, dict) and "Notes" in item
    ]
    assert len(notes_entries) == 1, "Expected exactly one Notes entry in nav"
    assert "notes/index.md" in notes_entries[0]["Notes"]
    assert "notes/chess_rules.md" in notes_entries[0]["Notes"]

    # Variant C: nav has - Notes: (None in parsed yaml)
    cfg_null = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
    cfg_null["nav"] = [{"Overview": "index.md"}, {"Notes": None}]
    cfg_null = mkdocs_hooks.on_config(cfg_null)
    notes_entries = [item for item in cfg_null["nav"] if isinstance(item, dict) and "Notes" in item]
    assert len(notes_entries) == 1, "Expected exactly one Notes entry in nav (no duplicates)"
    assert isinstance(notes_entries[0]["Notes"], list), "Notes entry must be mutated to a list"
    assert "notes/index.md" in notes_entries[0]["Notes"]
    assert "notes/chess_rules.md" in notes_entries[0]["Notes"]

    # Pipeline test: on_files correctly creates virtual files
    files = Files([])
    files = mkdocs_hooks.on_files(files, cfg_null)
    file_map = {f.src_uri: f for f in files}
    assert "notes/index.md" in file_map
    assert "notes/chess_rules.md" in file_map


def test_dynamic_notes_missing_or_empty_notes_dir(monkeypatch):
    """Verify behavior when notes/ directory does not exist or is empty."""
    import tempfile
    import mkdocs.config
    from mkdocs.structure.files import Files
    import sys

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    scripts_dir = os.path.join(repo_root, ".github", "scripts")
    if scripts_dir in sys.path:
        sys.path.remove(scripts_dir)
    sys.path.insert(0, scripts_dir)
    sys.modules.pop("mkdocs_hooks", None)

    import mkdocs_hooks

    # 1. Missing notes directory
    with tempfile.TemporaryDirectory() as tmp_dir:
        monkeypatch.chdir(tmp_dir)
        fake_src = os.path.join(tmp_dir, "src")
        os.makedirs(fake_src)

        cfg = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
        cfg["docs_dir"] = fake_src
        cfg["nav"] = [{"Overview": "index.md"}]
        cfg = mkdocs_hooks.on_config(cfg)
        notes_entry = next(
            (item for item in cfg["nav"] if isinstance(item, dict) and "Notes" in item), None
        )
        assert notes_entry is None, "Notes section should not be added when notes/ dir is missing"

        files = Files([])
        files = mkdocs_hooks.on_files(files, cfg)
        file_map = {f.src_uri: f for f in files}
        assert "notes/index.md" not in file_map
        if "index.md" in file_map:
            assert "Architecture & Reference Notes" not in getattr(
                file_map["index.md"], "_content", ""
            )

    # 2. Empty notes directory
    with tempfile.TemporaryDirectory() as tmp_dir:
        monkeypatch.chdir(tmp_dir)
        fake_src = os.path.join(tmp_dir, "src")
        os.makedirs(fake_src)
        fake_notes = os.path.join(tmp_dir, "notes")
        os.makedirs(fake_notes)

        cfg = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
        cfg["docs_dir"] = fake_src
        cfg["nav"] = [{"Overview": "index.md"}]
        cfg = mkdocs_hooks.on_config(cfg)
        notes_entry = next(
            (item for item in cfg["nav"] if isinstance(item, dict) and "Notes" in item), None
        )
        assert notes_entry is None, "Notes section should not be populated when notes/ dir is empty"

        files = Files([])
        files = mkdocs_hooks.on_files(files, cfg)
        file_map = {f.src_uri: f for f in files}
        assert "notes/index.md" not in file_map
        if "index.md" in file_map:
            assert "Architecture & Reference Notes" not in getattr(
                file_map["index.md"], "_content", ""
            )

    # 3. Directory ending in .md inside notes directory (Finding 4)
    with tempfile.TemporaryDirectory() as tmp_dir:
        monkeypatch.chdir(tmp_dir)
        fake_src = os.path.join(tmp_dir, "src")
        os.makedirs(fake_src)
        fake_notes = os.path.join(tmp_dir, "notes")
        os.makedirs(fake_notes)
        fake_subdir = os.path.join(fake_notes, "subfolder.md")
        os.makedirs(fake_subdir)

        cfg = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
        cfg["docs_dir"] = fake_src
        cfg["nav"] = [{"Overview": "index.md"}]
        cfg = mkdocs_hooks.on_config(cfg)
        notes_entry = next(
            (item for item in cfg["nav"] if isinstance(item, dict) and "Notes" in item), None
        )
        assert (
            notes_entry is None or "notes/subfolder.md" not in notes_entry["Notes"]
        ), "Directory ending with .md must not be added to nav"


def test_dynamic_notes_existing_index_md_on_disk():
    """Verify that an existing on-disk notes/index.md is preserved and not overwritten."""
    import mkdocs.config
    from mkdocs.structure.files import get_files
    import sys

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    scripts_dir = os.path.join(repo_root, ".github", "scripts")
    if scripts_dir in sys.path:
        sys.path.remove(scripts_dir)
    sys.path.insert(0, scripts_dir)
    sys.modules.pop("mkdocs_hooks", None)

    import mkdocs_hooks

    notes_index_path = os.path.join(repo_root, "notes", "index.md")
    custom_content = "# Real Hub Page On Disk\n\nThis is a hand-written index.md page."

    assert not os.path.exists(notes_index_path), "notes/index.md should not exist before test"
    try:
        with open(notes_index_path, "w", encoding="utf-8") as f:
            f.write(custom_content)

        cfg = mkdocs.config.load_config(os.path.join(repo_root, "mkdocs.yml"))
        cfg = mkdocs_hooks.on_config(cfg)
        files = get_files(cfg)
        files = mkdocs_hooks.on_files(files, cfg)

        file_map = {f.src_uri: f for f in files}
        assert "notes/index.md" in file_map, "notes/index.md must be generated"
        gen_file = file_map["notes/index.md"]
        assert (
            getattr(gen_file, "_content", "") == custom_content
        ), "Existing on-disk notes/index.md was overwritten by synthetic content"
        assert "# Architecture & Design Notes" not in getattr(gen_file, "_content", "")
    finally:
        if os.path.exists(notes_index_path):
            os.remove(notes_index_path)


def test_mkdocs_config_and_strict_build():
    import sys

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    mkdocs_yml = os.path.join(repo_root, "mkdocs.yml")
    assert os.path.isfile(mkdocs_yml), "mkdocs.yml must exist at repository root"

    cmd = [sys.executable, "-m", "mkdocs", "build", "--strict"]
    result = subprocess.run(cmd, cwd=repo_root, capture_output=True, text=True)
    assert (
        result.returncode == 0
    ), f"mkdocs build --strict failed with code {result.returncode}:\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"


def test_deploy_docs_workflow_exists():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    workflow_path = os.path.join(repo_root, ".github", "workflows", "deploy-docs.yml")

    assert os.path.isfile(workflow_path), "deploy-docs.yml workflow must exist"
    with open(workflow_path, encoding="utf-8") as f:
        content = f.read()

    assert "Deploy Documentation" in content
    assert "mkdocs build --strict" in content
    assert "upload-pages-artifact" in content
    assert "deploy-pages" in content


def test_agents_rule_mandates_google_docstrings_and_mkdocs():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    agents_file = os.path.join(repo_root, "AGENTS.md")

    with open(agents_file, encoding="utf-8") as f:
        content = f.read()

    assert "Google-style" in content or "Google-Style" in content
    assert "mkdocs build --strict" in content
    assert "GitHub Pages" in content
