import os
import pytest


def test_docs_index_references_all_documentation():
    """Verify that documentation is 100% autogenerated and static DOCS.md / docs/*.md are removed."""
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    docs_md = os.path.join(repo_root, "DOCS.md")
    docs_dir = os.path.join(repo_root, "docs")

    assert not os.path.exists(docs_md), "DOCS.md should not exist (superseded by dynamic docs)"
    md_files = [f for root, _, files in os.walk(docs_dir) for f in files if f.endswith(".md")]
    assert md_files == [], f"No static markdown files should be stored in docs/, found: {md_files}"


def test_agents_rule_requires_index_update():
    """Verify AGENTS.md mandates autogenerated documentation via MkDocs."""
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    agents_file = os.path.join(repo_root, "AGENTS.md")

    with open(agents_file, encoding="utf-8") as f:
        content = f.read()

    assert "mkdocs" in content.lower()
    assert "autogenerated" in content.lower()
